- name: Configure Nodejs
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install Nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Create a Roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Create an APP directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and unarchive Catalogue
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes

- name: Install Nodejs dependencies
  community.general.npm:
    path: /app
    state: latest

- name: Copy catalogue service file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Make sure a catalogue service unit is running
  ansible.builtin.systemd:
    state: restarted
    name: catalogue
    daemon_reload: yes
    enabled: yes