

- name: Create an Application Roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Remove old App content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create an APP directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and unarchive {{component}}
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes
