- name: Configure Nodejs
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: App prereq
  ansible.builtin.include_tasks: "app-prereq.yml"
  when: schema_load


- name: Install Nodejs dependencies
  community.general.npm:
    path: /app
    state: latest

- name: Systemd setup
  ansible.builtin.include_tasks: "systemd.yml.yml"
  when: schema_load

- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-mongodb-schema.yml"
  when: schema_load



